### ISSUE TITLE
运行出现异常

### ISSUE THREAD

**Issue by cnkerry** [micahh28/HHAutoUpdate.NET#1]
运行就出现：
索引超出数组界限

**Comment by cnkerry** [comment]
Program.cs
string launchAppName = args[0];

**Comment by Chadwuo** [comment]
在string launchAppName = args[0]代码前给args赋值初始化。例如 args = new string []{"test","0"}.
这个项目中没有这样赋值的原因，是因为赋值的工作应给由发起更新的应用程序在调用时传递

**Comment by cnkerry** [comment]
感谢
