### ISSUE TITLE
win10 vs2022 执行demo程序报错

### ISSUE THREAD

**Issue by qq492269704** [micahh28/HHAutoUpdate.NET#3]
【日志级别】ERROR                                   
【记录时间】2022-06-19 22:02:40,719                                   
【线程编号】[1]                                   
【执行时间】[3124]毫秒                                   
【引发位置】G:\HHAutoUpdate.NET-master\HHAutoUpdate.NET-master\HHUpdateApp\UpdateForm.cs                                   
【引发行号】87                                   
【消息描述】更新应用程序升级失败：                                   
【消息详情】System.UnauthorizedAccessException: 对路径“G:\HHAutoUpdate.NET-master\HHAutoUpdate.NET-master\Demo\bin\Debug\DotNetZip.dll”的访问被拒绝。
   在 HHUpdateApp.UpdateWork.DelLocal() 位置 G:\HHAutoUpdate.NET-master\HHAutoUpdate.NET-master\HHUpdateApp\UpdateWork.cs:行号 282
   在 HHUpdateApp.UpdateWork.Restore() 位置 G:\HHAutoUpdate.NET-master\HHAutoUpdate.NET-master\HHUpdateApp\UpdateWork.cs:行号 248
   在 HHUpdateApp.UpdateWork.Update() 位置 G:\HHAutoUpdate.NET-master\HHAutoUpdate.NET-master\HHUpdateApp\UpdateWork.cs:行号 181
   在 HHUpdateApp.UpdateForm.BGWorkerUpdate_DoWork(Object sender, DoWorkEventArgs e) 位置 G:\HHAutoUpdate.NET-master\HHAutoUpdate.NET-master\HHUpdateApp\UpdateForm.cs:行号 47
   在 System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   在 System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

设置了权限还是提示这个，请问大佬能指点一下吗

**Comment by Chadwuo** [comment]
更新升级的软件包，不能包含 HHAutoUpdate.exe

**Comment by 429290005** [comment]
【日志级别】ERROR                                   
【记录时间】2022-07-16 11:28:41,179                                   
【线程编号】[1]                                   
【执行时间】[4932]毫秒                                   
【引发位置】F:\MyCode@GitHub\HHUpdateApp\HHUpdateApp\UpdateForm.cs                                   
【引发行号】88                                   
【消息描述】更新应用程序升级失败：                                   
【消息详情】System.UnauthorizedAccessException: 对路径“C:\Users\dell\AppData\Local\Temp\HHUpdateApp\bak\PilotClient.exe.config”的访问被拒绝。
   在 HHUpdateApp.UpdateWork.Bak() 位置 F:\MyCode@GitHub\HHUpdateApp\HHUpdateApp\UpdateWork.cs:行号 153
   在 HHUpdateApp.UpdateForm.BGWorkerUpdate_DoWork(Object sender, DoWorkEventArgs e) 位置 F:\MyCode@GitHub\HHUpdateApp\HHUpdateApp\UpdateForm.cs:行号 41
   在 System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   在 System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

这个是什么原因啊

**Comment by micahh28** [comment]
C:\Users\dell\AppData\Local\Temp\HHUpdateApp\bak\

**Comment by Chadwuo** [comment]
C:\Users\dell\AppData\Local\Temp\HHUpdateApp\bak\PilotClient.exe.config
是对你程序的备份，具体什么原因不能操作PilotClient.exe.config，我就不清楚了
